-- Set default char set, settings supports unicode and emoji
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
ALTER DATABASE appDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- Create table for autogenerated hibernate IDs
CREATE TABLE `hibernate_sequence` (`next_val` BIGINT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO `hibernate_sequence` (next_val) VALUES(2);

-- store basic P1 user info
CREATE TABLE `users` (
  `id` BIGINT NOT NULL,
  `email` VARCHAR(100),
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tasks`(
    `id` BIGINT NOT NULL,
    `detail` TINYTEXT NOT NULL,
    `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `user_id` BIGINT,
    `is_complete` BIT(1) DEFAULT FALSE,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES users(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
